version: 0.1
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
     - pwd
     - ls
 build:
   commands:
     - aws s3 sync --delete website/ "s3://thomas-lemoullec.com/projects/airbnb-advisor/"
     - aws s3 cp "website/index.html" "s3://thomas-lemoullec.com/"
     - aws s3 cp "website/index.html" "s3://thomas-lemoullec.com/projects"
     - aws s3 cp "website/index.html" "s3://thomas-lemoullec.com/projects/airbnb-advisor"
 post_build:
   commands:
     - echo "post_build step"
