version: 0.1
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete "s3://thomas-lemoullec.com/projects/airbnb-advisor/"
 post_build:
   commands:
     - echo "post_build step"
